# Items
glitch:
  name: "АбОбф10"
  icon: "aboba1"
  coolness:
    name: "Крутость" 
    value: 4
  useability:
    name: "Полезность" 
    value: 3
aboba:
  name: "ABOBA"
  icon: "aboba2"
  coolness:
    name: "Крутость" 
    value: 65
  useability:
    name: "Полезность" 
    value: 7
