itemname:
  name: "Секира" 
  icon: none
  attribute1:
    name: "Прочность" 
    value: 2675
  attribute2:
    name: "Урон"
    value: 14
    valuemax: 16

itemname2:
  name: "Ручка СекБи" 
  icon: none
  attribute1:
    name: "Прочность" 
    value: 70
  attribute2:
    name: "Урон"
    value: 10
  attribute3:
    name: "Холодотность" 
    value: 500
