# Items
axe:
  name: "Секира"
  icon: none
  rarity:
    name: "Редкость" 
    value: "Обычный"
  durability:
    name: "Прочность" 
    value: 400
  damage:
    name: "Урон"
    value: 8
  critDamage:
    name: "Крит. Урон"
    value: 12
  attackSpeed:
    name: "Скорость Атаки"
    value: "0.8 ударов/с"
